on:
  pull_request:
    branches: [ "*" ]

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow_ref}}${{github.ref_name}}

jobs:
  detect-changes:
    uses: ./.github/workflows/detect_changes.yml
    permissions: 
      pull-requests: read
      contents: read

  clearco-webapp-build-validate-impl:
    needs: detect-changes
    if: needs.detect-changes.outputs.clearco-webapp == 'true'
    uses: ./.github/workflows/build_validate_webapp.yml
    with: 
      project-directory: clearco-webapp
    permissions: 
      contents: read

  clearco-webapp-build-validate:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.clearco-webapp == 'true'
    steps:
    - run: |
        echo foo

  cc-reacthost-build-validate:
    needs: detect-changes
    if: needs.detect-changes.outputs.cc-reacthost == 'true'
    uses: ./.github/workflows/build_validate_dotnet.yml
    with: 
      project-directory: Cc.ReactHost
    secrets: inherit
    permissions: 
      contents: read

  cc-webbff-build-validate:
    needs: detect-changes
    if: needs.detect-changes.outputs.cc-webbff == 'true'
    uses: ./.github/workflows/build_validate_dotnet.yml
    with: 
      project-directory: Cc.WebBff
    secrets: inherit
    permissions: 
      contents: read
