name: Print Version

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{vars.CURRENT_PERFORMANCE_VERSION}}"
